---
# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

# =============================================================================
# BASIC CONFIGURATION
# =============================================================================
language: en-US
tone_instructions: ""
early_access: true
enable_free_tier: true
