packages:
  - packages/*
overrides:
  ioredis: 6.0.0
allowBuilds:
  '@datadog/native-appsec': false
  '@datadog/native-iast-taint-tracking': false
  '@datadog/native-metrics': false
  '@datadog/pprof': false
  dd-trace: false
  esbuild: false
  msgpackr-extract: false
  msw: false
  protobufjs: false
  tls-impersonate: false
minimumReleaseAgeExclude:
  - "@lokalise/errors"
  - "@lokalise/fastify-extras"
