#!/bin/bash

# =============================================================================
# CodeRabbit Configuration Builder
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/../.coderabbit.yaml"

echo "🔨 Building CodeRabbit configuration..."

# Create the main config file with header
cat > "$OUTPUT_FILE" << 'EOF'
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
# =============================================================================
# This file is generated by .coderabbit/build.sh
# Edit files in .coderabbit/config/ directory and run './.coderabbit/build.sh'
# =============================================================================

# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

EOF

# Function to remove YAML document separators and schema lines
remove_yaml_separators() {
    sed '/^---$/d' | sed '/^# yaml-language-server:/d'
}

# Function to extract content under a specific YAML key
extract_yaml_content() {
    local key="$1"
    sed -n "/^${key}:$/,\$p" | sed '1d'
}

# Combine all configuration files in order
echo "📝 Combining configuration files..."

echo "   ➤ Adding base.yml"
cat "$SCRIPT_DIR/config/base.yml" | remove_yaml_separators >> "$OUTPUT_FILE"

echo "   ➤ Adding review-settings.yml"
# Add review settings, trimming only trailing blank lines
cat "$SCRIPT_DIR/config/review-settings.yml" | remove_yaml_separators | awk 'NF {p=1} p' >> "$OUTPUT_FILE"

echo "   ➤ Adding tools.yml under reviews"
# Add tools under the reviews section
echo -e "\n  tools:" >> "$OUTPUT_FILE"
cat "$SCRIPT_DIR/config/tools.yml" | remove_yaml_separators | extract_yaml_content "tools" | sed 's/^/  /' >> "$OUTPUT_FILE"

echo "   ➤ Adding chat-knowledge.yml"
echo -e "\n" >> "$OUTPUT_FILE"  # Add blank line before next section
cat "$SCRIPT_DIR/config/chat-knowledge.yml" | remove_yaml_separators >> "$OUTPUT_FILE"

# Remove trailing spaces
sed -i '' 's/[[:space:]]*$//' "$OUTPUT_FILE"

echo ""
echo "✅ CodeRabbit configuration built successfully!"
echo "📄 Output: .coderabbit.yaml"
echo ""
echo "📊 Configuration summary:"
echo "   • $(grep -c "enabled: true" "$OUTPUT_FILE") tools enabled"
echo "   • $(wc -l < "$OUTPUT_FILE") total lines"
echo ""
echo "🚀 Ready to use! Commit .coderabbit.yaml to apply changes."